Neos:
  Neos:
    fusion:
      autoInclude:
        NeosRulez.ScssParser: true
NeosRulez:
  ScssParser:
    format: compressed
    #format: expanded
    #format: nested
    #format: compact
    #format: crunched